--cau1
SELECT * FROM KHOAHOC;
SELECT * FROM CHUONGTRINH;
SELECT * FROM LOAILOP;
SELECT * FROM LOP;
SELECT * FROM HOCVIEN;
SELECT * FROM PHIEUTHU;
SELECT * FROM MONHOC;
SELECT * FROM DIEM;
--cau2
SELECT * FROM HOCVIEN
WHERE GIOITINH = 1;
--cau3
SELECT * FROM HOCVIEN
WHERE DIACHI LIKE '%Cần Thơ%';
--cau4
SELECT * FROM LOP
WHERE MAKH = (
    SELECT MAKH FROM KHOAHOC WHERE TENKH = 'Khóa 1'
);
--cau5
SELECT DISTINCT HV.MAHV, HV.TENHV
FROM HOCVIEN HV
JOIN PHIEUTHU PT ON HV.MAHV = PT.MAHV
JOIN LOP L ON PT.MALOP = L.MALOP
JOIN KHOAHOC KH ON L.MAKH = KH.MAKH
WHERE KH.TENKH = 'Khóa 1';
--cau6
SELECT * FROM HOCVIEN
WHERE TENHV LIKE '%Đỗ%';
--cau7
SELECT * FROM HOCVIEN
WHERE NGAYSINH LIKE '%2000%';
SELECT * FROM HOCVIEN
WHERE EXTRACT(YEAR FROM NGAYSINH) = 2000;
--cau8
SELECT * FROM HOCVIEN
WHERE EXTRACT(YEAR FROM NGAYSINH) = 2001
AND EXTRACT(MONTH FROM NGAYSINH) = 12;
--cau9
SELECT * FROM HOCVIEN
WHERE EXTRACT(YEAR FROM NGAYSINH) BETWEEN 1998 AND 2000;
--cau10
SELECT * FROM PHIEUTHU
WHERE NGAYLAPPHIEU BETWEEN TO_DATE('2021-06-05','YYYY-MM-DD') AND TO_DATE('2021-06-10','YYYY-MM-DD');
--cau11
SELECT HV.* FROM HOCVIEN HV
JOIN PHIEUTHU PT ON HV.MAHV = PT.MAHV
JOIN LOP L ON PT.MALOP = L.MALOP
JOIN LOAILOP LL ON L.MALOAI = LL.MALOAI
WHERE L.TENLOP = 'Lớp 1'
AND LL.TENLOAI = 'Tiếng anh căn bản';
--cau12
SELECT L.* 
FROM LOP L
JOIN LOAILOP LL ON L.MALOAI = LL.MALOAI
JOIN CHUONGTRINH CT ON LL.MACT = CT.MACT
WHERE CT.TENCT = 'Tiếng Anh Tổng Quát';
--cau13
SELECT PT.*
FROM PHIEUTHU PT
JOIN LOP L ON PT.MALOP = L.MALOP
JOIN LOAILOP LL ON L.MALOAI = LL.MALOAI
WHERE L.TENLOP = 'Lớp 1'
AND LL.TENLOAI = 'Tiếng Anh A1';
--cau14
SELECT HV.TENHV, MH.TENMH, D.DIEM
FROM HOCVIEN HV
JOIN DIEM D ON HV.MAHV = D.MAHV
JOIN MONHOC MH ON D.MAMH = MH.MAMH
JOIN LOP L ON D.MALOP = L.MALOP
JOIN KHOAHOC KH ON L.MAKH = KH.MAKH
WHERE KH.TENKH = 'Khóa 1';
--cau15
SELECT COUNT(*) AS TONG_HOCVIEN
FROM HOCVIEN;
--cau16
SELECT COUNT(DISTINCT PT.MAHV) AS SO_HOCVIEN
FROM PHIEUTHU PT
JOIN LOP L ON PT.MALOP = L.MALOP
JOIN LOAILOP LL ON L.MALOAI = LL.MALOAI
WHERE L.TENLOP = 'Lớp 1'
AND LL.TENLOAI = 'Tiếng Anh căn bản';
--cau20
SELECT MAX(DIEM) AS DIEM_CAO_NHAT
FROM DIEM;
--cau17
SELECT SUM(PT.THANHTIEN) AS TONG_THU
FROM PHIEUTHU PT
JOIN LOP L ON PT.MALOP = L.MALOP
JOIN LOAILOP LL ON L.MALOAI = LL.MALOAI
WHERE L.TENLOP = 'Lớp 1'
AND LL.TENLOAI = 'Tiếng Anh căn bản';
--cau18
SELECT SUM(PT.THANHTIEN) AS THU
FROM PHIEUTHU PT
JOIN LOP L ON PT.MALOP = L.MALOP
JOIN KHOAHOC KH ON L.MAKH = KH.MAKH
WHERE KH.TENKH = 'Khóa 1';
--cau19
SELECT AVG(D.DIEM) AS DIEM_TRUNGBINH
FROM DIEM D
JOIN HOCVIEN HV ON D.MAHV = HV.MAHV
JOIN LOP L ON D.MALOP = L.MALOP
JOIN LOAILOP LL ON L.MALOAI = LL.MALOAI
WHERE HV.TENHV = 'Đỗ Gia Bảo'
AND HV.NGAYSINH = TO_DATE('2001-12-02','YYYY-MM-DD')
AND L.TENLOP = 'Lớp 1'
AND LL.TENLOAI = 'Tiếng Anh căn bản';